### ISSUE TITLE
Move repo to Dracula's official org

### ISSUE THREAD

**Issue by zenorocha** [dracula/light-table#1]
Hello @DamianK!

I'm the creator of Dracula color scheme. I was searching for themes created by the community and I found yours. Good job by the way!

I was wondering if you are interested in transferring this repository to the official organization (https://github.com/dracula). You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

What do you think?

**Comment by DamianK-zz** [comment]
Hi Zeno! Sure it’ll be a pleasure to work on this. Let me know what I have to do.
Regards,
Damian

**Comment by zenorocha** [comment]
First, let's try transferring the repository.

Go to https://github.com/DamianK/lighttable-dracula-theme/settings and select `Transfer`.

Then, apply this template (https://github.com/dracula/template) which includes `README`, `LICENSE`, and `.github`.

**Comment by DamianK-zz** [comment]
Zeno, its already transferred I'll work on the readme template in a while today, let me know if you see everything ok. 
Regards
Damian

**Comment by zenorocha** [comment]
Awesome! By the way, I just renamed the repo to match the other ones.

**Comment by DamianK-zz** [comment]
Perfect! I'll work on it.
Regards
Damian

**Comment by DamianK-zz** [comment]
Zeno, I changed the License & Readme. Please check and let me know if I need to change anything else. Also, let me know if you need help with the install page for lighttable theme on draculatheme.com page or anything else.
Regards
Damian

**Comment by zenorocha** [comment]
That's great. Could you also update the repository description to be like the other ones?

About the site, I'll use your previous instructions and screenshot to update it.

P.S.: I don't deserve any credits, you did all the work :) https://github.com/dracula/light-table/commit/342f976f8ed1d82e526fcd20fc93d6a7d1f82d87

**Comment by DamianK-zz** [comment]
Ok i'll update description. Also, I think you really deserve some credit because you did the original one :) 

Regards.

**Comment by DamianK-zz** [comment]
Zeno, I think everything is in place, you only need to setup the page in draculatheme.com for light-table. Let me know if I should do anything else.
Regards
Damian

**Comment by zenorocha** [comment]
There you go! https://draculatheme.com/light-table/

Let me know if you want to change anything ;)
